# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geek-Hub Life
email: suhan.lee.k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Android, Web, Media, Game Hacker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://suhanlee.github.io" # the base hostname & protocol for your site
twitter_username: gabriel_rhee
github_username:  suhanlee

# Build settings
markdown: kramdown
